/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multipanel;

import Clases.ProbSubEMUL;

/**
 *
 * @author danie
 */
public class jpanelEMUL extends javax.swing.JPanel {

    /**
     * Creates new form jpanelEsAD1
     */
    public jpanelEMUL() {
        initComponents();
        Limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNroDatos = new javax.swing.JLabel();
        cbVariables = new javax.swing.JComboBox();
        lbltituloFormula = new javax.swing.JLabel();
        lblFormula = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblPA = new javax.swing.JLabel();
        lblPB = new javax.swing.JLabel();
        txtPB = new javax.swing.JTextField();
        txtPA = new javax.swing.JTextField();
        lblPC = new javax.swing.JLabel();
        lblPD = new javax.swing.JLabel();
        txtPD = new javax.swing.JTextField();
        txtPC = new javax.swing.JTextField();
        lblPE = new javax.swing.JLabel();
        txtPE = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblResultado = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        lblNroDatos.setText("Nro de variables");

        cbVariables.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        cbVariables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVariablesActionPerformed(evt);
            }
        });

        lbltituloFormula.setText("FORMULA REGLA ESPECIAL DE MULTIPLICACIÓN");

        lblFormula.setText("P(A y B y C)= P(A) x P(B) x P(C)");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        lblPA.setText("P(A)");

        lblPB.setText("P(B)");

        lblPC.setText("P(C)");

        lblPD.setText("P(D)");

        lblPE.setText("P(E)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblPA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblPB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblPD)
                        .addGap(18, 18, 18)
                        .addComponent(txtPD, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblPC)
                        .addGap(18, 18, 18)
                        .addComponent(txtPC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPA)
                    .addComponent(lblPC)
                    .addComponent(lblPE)
                    .addComponent(txtPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPB)
                    .addComponent(lblPD)
                    .addComponent(txtPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiar)
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNroDatos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbVariables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbltituloFormula)
                                .addGap(18, 18, 18)
                                .addComponent(lblFormula)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNroDatos)
                    .addComponent(cbVariables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltituloFormula)
                    .addComponent(lblFormula))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiar)
                    .addComponent(btnCalcular))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbVariablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVariablesActionPerformed
        // TODO add your handling code here:
        int nro = cbVariables.getSelectedIndex() + 1;
        if(nro==1){
            lblPA.setVisible(true);  txtPA.setVisible(true);
            lblPB.setVisible(false); txtPB.setVisible(false);
            lblPC.setVisible(false); txtPC.setVisible(false);
            lblPD.setVisible(false); txtPD.setVisible(false);
            lblPE.setVisible(false); txtPE.setVisible(false);
        }
        else if(nro==2){
            lblPA.setVisible(true);  txtPA.setVisible(true);
            lblPB.setVisible(true);  txtPB.setVisible(true);
            lblPC.setVisible(false); txtPC.setVisible(false);
            lblPD.setVisible(false); txtPD.setVisible(false);
            lblPE.setVisible(false); txtPE.setVisible(false);
        }
        else if(nro==3){
            lblPA.setVisible(true);  txtPA.setVisible(true);
            lblPB.setVisible(true);  txtPB.setVisible(true);
            lblPC.setVisible(true);  txtPC.setVisible(true);
            lblPD.setVisible(false); txtPD.setVisible(false);
            lblPE.setVisible(false); txtPE.setVisible(false);
        }
        else if(nro==4){
            lblPA.setVisible(true);  txtPA.setVisible(true);
            lblPB.setVisible(true);  txtPB.setVisible(true);
            lblPC.setVisible(true);  txtPC.setVisible(true);
            lblPD.setVisible(true);  txtPD.setVisible(true);
            lblPE.setVisible(false); txtPE.setVisible(false);
        }
        else if(nro==5){
            lblPA.setVisible(true);  txtPA.setVisible(true);
            lblPB.setVisible(true);  txtPB.setVisible(true);
            lblPC.setVisible(true);  txtPC.setVisible(true);
            lblPD.setVisible(true);  txtPD.setVisible(true);
            lblPE.setVisible(true); txtPE.setVisible(true);
        }

    }//GEN-LAST:event_cbVariablesActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:

        double array[]= new double[cbVariables.getSelectedIndex()+1];
        if(array.length==1){
            array[0]=Double.parseDouble(txtPA.getText());
        }else if(array.length==2){
            array[0]=Double.parseDouble(txtPA.getText());
            array[1]=Double.parseDouble(txtPB.getText());
        }else if(array.length==3){
            array[0]=Double.parseDouble(txtPA.getText());
            array[1]=Double.parseDouble(txtPB.getText());
            array[2]=Double.parseDouble(txtPC.getText());
        }else if(array.length==4){
            array[0]=Double.parseDouble(txtPA.getText());
            array[1]=Double.parseDouble(txtPB.getText());
            array[2]=Double.parseDouble(txtPC.getText());
            array[3]=Double.parseDouble(txtPD.getText());
        }else if(array.length==5){
            array[0]=Double.parseDouble(txtPA.getText());
            array[1]=Double.parseDouble(txtPB.getText());
            array[2]=Double.parseDouble(txtPC.getText());
            array[3]=Double.parseDouble(txtPD.getText());
            array[4]=Double.parseDouble(txtPE.getText());
        }
        ProbSubEMUL obj= new ProbSubEMUL(array);
        obj.Calcular();
        lblResultado.setText(obj.toString());
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed


    public void Limpiar(){
        lblPA.setVisible(false); txtPA.setVisible(false);
        lblPB.setVisible(false); txtPB.setVisible(false);
        lblPC.setVisible(false); txtPC.setVisible(false);
        lblPD.setVisible(false); txtPD.setVisible(false);
        lblPE.setVisible(false); txtPE.setVisible(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox cbVariables;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblFormula;
    private javax.swing.JLabel lblNroDatos;
    private javax.swing.JLabel lblPA;
    private javax.swing.JLabel lblPB;
    private javax.swing.JLabel lblPC;
    private javax.swing.JLabel lblPD;
    private javax.swing.JLabel lblPE;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lbltituloFormula;
    private javax.swing.JTextField txtPA;
    private javax.swing.JTextField txtPB;
    private javax.swing.JTextField txtPC;
    private javax.swing.JTextField txtPD;
    private javax.swing.JTextField txtPE;
    // End of variables declaration//GEN-END:variables
}
